export { default as AuthNavigate } from './AuthNavigate/AuthNavigate';
export { default as Container } from './Container/Container';
export { default as MainTitle } from './MainTitle/MainTitle';
export { default as Modal } from './Modal/Modal';
export { default as Section } from './Section/Section';
export { default as Spinner } from './Spinner/Spinner';
export { default as SubTitle } from './SubTitle/SubTitle';
export { default as TaskForm } from './TaskForm/TaskForm';
export { default as TaskModal } from './TaskModal/TaskModal';
